
SWIGABLE_C=						\

LIB_C=							\

EXPLORER_C =	       			\
	model_states_explorer		\
	model_features_explorer		\

SWIGABLE_ADA= 					\

EXPLORER_ADA =	       			\

include $(K2)/tools/generic_rules.mk

